name: CI-CD

on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore
        run: npm ci
      - name: Styling
        run: npm run styling:ci
      - name: Test
        run: npm test

      - name: Publish Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: false
